version: '3'
services:
  backend:
    image: nodejsshop 
    ports:
      - "3000:3000"  
    networks:
      - app-net
    environment:
      - DATABASE_URL=mongodb://mongo:27017/shoping_database 
      - MONGODB_URL=mongodb://mongo:27017/shoping_database
      - MONGO_DEFAULT_DATABASE = shoping_database

  frontend:
    image: frontend
    networks:
      - app-net
    environment:
      - API_URL=http://localhost:3000

  mongo:
    image: mongo
    ports:
      - "27017:27017"  
    networks:
      - app-net
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: pass
      ME_CONFIG_SITE_ENABLE_ADMIN: true
      ME_CONFIG_SITE_ENABLE_DEBUGGER: true
      ME_CONFIG_SITE_ENABLE_TRIGGERS: true
  nginx:
    image: nginx-proxy
    ports:
      - "8080:80"    
      - "8443:443" 
    networks:
      - app-net
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d  
    depends_on:
      - backend
      - frontend
      - mongo
    environment:
      - NGINX_PROXY_BACKEND=frontend:3000

networks:
  app-net:
