apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-express-config
data:
  ME_CONFIG_MONGODB_SERVER: mongo-service 
  ME_CONFIG_MONGODB_PORT: "27017" # Default MongoDB port
  ME_CONFIG_MONGODB_DATABASE: mydatabase
  ME_CONFIG_MONGODB_USERNAME: username 
  ME_CONFIG_MONGODB_PASSWORD: password
