apiVersion: apps/v1
kind: Deployment
metadata:
 name: nginx-proxy
spec:
 replicas: 1
 selector:
   matchLabels:
     app: nginx-proxy
 template:
   metadata:
     labels:
       app: nginx-proxy
   spec:
     containers:
     - name: nginx
       image: nginx
       ports:
       - containerPort: 80
       - containerPort: 443
       volumeMounts:
       - name: nginx-config-volume
         mountPath: /etc/nginx/nginx.conf
         subPath: nginx.conf
       - name: nginx-certs
         mountPath: /etc/ssl/certs
         readOnly: true
       - name: nginx-keys
         mountPath: /etc/ssl/private
         readOnly: true
     volumes:
     - name: nginx-config-volume
       configMap:
         name: nginx-config
     - name: nginx-certs
       secret:
         secretName: nginx-certs
         items:
         - key: cert
           path: localhost.crt
     - name: nginx-keys
       secret:
         secretName: nginx-certs
         items:
         - key: key
           path: localhost.key
#kubectl apply -f nginx-deployment.yml