apiVersion: v1
kind: Service
metadata:
  name: shopping-service
spec:
  type: LoadBalancer
  selector:
    app: shopping
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 32000