apiVersion: apps/v1
kind: Deployment
metadata:
  name: shopping-deployment
  labels:
    app: shopping
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shopping
  template:
    metadata:
      labels:
        app: shopping
    spec:
      containers:
        - name: shopping
          imagePullPolicy: Always  # Change this line
          image: shopping
          ports:
            - containerPort: 3000
          env:
            - name: MONGODB_URI
              value: "mongodb://username:password@mongo-service:27017/shopping_database"

