#We don't want to start from scratch.
# That is why we tell node here to use the current node image as base.
FROM node:latest
ENV PORT=3003

# Create an application directory
RUN mkdir -p /usr/src/app

# The /usr/src/app directory should act as the main application directory
WORKDIR /usr/src/app

# Copy or project directory (locally) in the current directory of our docker image (/app)
COPY . /usr/src/app

# Build the app

# Expose $PORT on container.
# We use a varibale here as the port is something that can differ on the environment.
EXPOSE 3003

# Set the browser base url
ENV NODE_ENV=development

# Start the app
