#We don't want to start from scratch.
# That is why we tell node here to use the current node image as base.
FROM node:latest
ENV PORT=3003

# Create an application directory
RUN mkdir -p /usr/src/app

# The /usr/src/app directory should act as the main application directory
WORKDIR /usr/src/app

COPY . /usr/src/app


# Set the browser base url
ENV NODE_ENV=development
ENV PORT=3000
ENV MONGO_DEFAULT_DATABASE=shoping_database
ENV DATABASE_URL=mongodb://mongo:27017/shoppingdatabase
ENV MONGODB_URL=mongodb://mongo:27017/shoppingdatabase
ENV API_URL=http://localhost:3000
ENV ME_CONFIG_BASICAUTH_USERNAME: admin
ENV ME_CONFIG_BASICAUTH_PASSWORD: pass
ENV ME_CONFIG_MONGODB_URL: mongodb://mongo:27017/shoppingdatabase
ENV ME_CONFIG_MONGODB_SERVER: mongo
ENV ME_CONFIG_MONGODB_PORT: 27017
ENV ME_CONFIG_MONGODB_ENABLE_ADMIN: true
ENV ME_CONFIG_OPTIONS_EDITORTHEME: default
ENV NGINX_PROXY_BACKEND=shopping:3000

EXPOSE 3000

CMD ["npm", "start"]